const NAMESPACE = '@redux-auth';

export const REGISTER_START = `${NAMESPACE}/REGISTER_START`;
export const REGISTER_SUCCESS = `${NAMESPACE}/REGISTER_SUCCESS`;
export const REGISTER_ERROR = `${NAMESPACE}/REGISTER_ERROR`;

export const LOGIN_START = `${NAMESPACE}/LOGIN_START`;
export const LOGIN_SUCCESS = `${NAMESPACE}/LOGIN_SUCCESS`;
export const LOGIN_ERROR = `${NAMESPACE}/LOGIN_ERROR`;

export const LOGOUT_START = `${NAMESPACE}/LOGOUT_START`;
export const LOGOUT_SUCCESS = `${NAMESPACE}/LOGOUT_SUCCESS`;
export const LOGOUT_ERROR = `${NAMESPACE}/LOGOUT_ERROR`;

export const GET_USER_START = `${NAMESPACE}/GET_USER_START`;
export const GET_USER_SUCCESS = `${NAMESPACE}/GET_USER_SUCCESS`;
export const GET_USER_ERROR = `${NAMESPACE}/GET_USER_ERROR`;
