const NAMESPACE = 'POSTS';

export const FETCH_POSTS_START = `${NAMESPACE}/FETCH_POSTS_START`;
export const FETCH_POSTS_SUCCESS = `${NAMESPACE}/FETCH_POSTS_SUCCESS`;
export const FETCH_POSTS_ERROR = `${NAMESPACE}/FETCH_POSTS_ERROR`;
