const NAMESPACE = '@redux-posts';

export const LOAD_POSTS_START = `${NAMESPACE}/LOAD_POSTS_START`;
export const LOAD_POSTS_SUCCESS = `${NAMESPACE}/LOAD_POSTS_SUCCESS`;
export const LOAD_POSTS_ERROR = `${NAMESPACE}/LOAD_POSTS_ERROR`;
