const NAMESPACE = '@redux-news';

export const LOAD_NEWS_START = `${NAMESPACE}/LOAD_NEWS_START`;
export const LOAD_NEWS_SUCCESS = `${NAMESPACE}/LOAD_NEWS_SUCCESS`;
export const LOAD_NEWS_ERROR = `${NAMESPACE}/LOAD_NEWS_ERROR`;
